### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by BornaPexor** [DarkSkull777/blum-bot#1]
sometimes it tap bombs too

**Comment by AliEmili** [comment]
@BornaPexor 
change this line in code to: 

```
if (b in range(20, 125)) and (r in range(102, 220)) and (g in range(200, 255)):
```

**Comment by raishudesu** [comment]
> @BornaPexor change this line in code to:
> 
> ```
> if (b in range(20, 125)) and (r in range(102, 220)) and (g in range(200, 255)):
> ```

This still tap bombs sometimes
